Extract

In [5]:
import pandas as pd
import numpy as np
# Cargar el archivo para ver qu√© hojas tiene
excel_file = 'Copia de Lista de Estudiantes_2025_secundaria (1).xlsx'
sheet_names = pd.ExcelFile(excel_file).sheet_names
print("Hojas disponibles:")
for i, sheet in enumerate(sheet_names):
    print(f"{i}: {sheet}")

Hojas disponibles:
0: 1A_2025
1: 1B_2025
2: 1C_2025
3: 1D_2025
4: 2A_2025
5: 2B_2025
6: 2C_2025
7: 2D_2025
8: 3A_2025
9: 3B_2025
10: 3C_2025
11: 3D_2025
12: 4A_2025
13: 4B_2025
14: 4C_2025
15: 4D_2025
16: 5A_2025
17: 5B_2025
18: 5C_2025
19: 5D_2025

In [4]:
df.tail(10)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
33,NaN,25,DNI,81056948,NaN,NaN,NaN,00000081056948,NaN,PALOMINO,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,12/09/2012,12
34,NaN,26,DNI,77732374,NaN,NaN,NaN,00000077732374,NaN,PEREZ,...,NaN,NaN,NaN,NaN,Mujer,NaN,NaN,NaN,21/06/2012,12
35,NaN,27,DNI,77888510,NaN,NaN,NaN,00000077888510,NaN,PORTAL,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,24/11/2012,12
36,NaN,28,DNI,77841775,NaN,NaN,NaN,00000077841775,NaN,REMUZGO,...,NaN,NaN,NaN,NaN,Mujer,NaN,NaN,NaN,09/09/2012,12
37,NaN,29,DNI,77941119,NaN,NaN,NaN,00000077941119,NaN,RODAS,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,26/12/2012,12
38,NaN,30,DNI,77721091,NaN,NaN,NaN,00000077721091,NaN,SALAZAR,...,NaN,NaN,NaN,NaN,Mujer,NaN,NaN,NaN,02/06/2012,12
39,NaN,31,DNI,75631070,NaN,NaN,NaN,00000075631070,NaN,TOLEDO,...,NaN,NaN,NaN,NaN,Mujer,NaN,NaN,NaN,27/12/2010,14
40,NaN,32,DNI,77611244,NaN,NaN,NaN,00000077611244,NaN,TORREJON,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,21/03/2012,13
41,NaN,33,DNI,77896925,NaN,NaN,NaN,00000077896925,NaN,VARGAS,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,19/10/2012,12
42,NaN,34,DNI,63793819,NaN,NaN,NaN,00000063793819,NaN,VIVANCO,...,NaN,NaN,NaN,NaN,Hombre,NaN,NaN,NaN,17/06/2012,12

In [6]:
all_sheets = pd.read_excel(excel_file, sheet_name=None)

# Ver cu√°ntas hojas hay
print(f"N√∫mero total de hojas: {len(all_sheets)}")

# Acceder a cada hoja
for sheet_name, df in all_sheets.items():
    print(f"\nHoja: {sheet_name}")
    print(f"Dimensiones: {df.shape}")
    print(df.head(2))

N√∫mero total de hojas: 20

Hoja: 1A_2025
Dimensiones: (43, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN         NaN        NaN
1         NaN        NaN        NaN        NaN         NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     15:33:20

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 1B_2025
Dimensiones: (42, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3  Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN         NaN        NaN
1         NaN        NaN        NaN        NaN         NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     15:43:12

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 1C_2025
Dimensiones: (44, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     15:49:20

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 1D_2025
Dimensiones: (43, 25)
   Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN         NaN        NaN        NaN        NaN        NaN
1         NaN         NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     15:55:25

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 2A_2025
Dimensiones: (43, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN      16:2:44

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 2B_2025
Dimensiones: (44, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN      16:7:14

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 2C_2025
Dimensiones: (47, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     16:12:50

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 2D_2025
Dimensiones: (43, 27)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 17 Unnamed: 18 Unnamed: 19  Unnamed: 20  \
0        NaN  ...         NaN        HORA         NaN          NaN
1        NaN  ...         NaN     16:26:1         NaN          NaN

  Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 27 columns]

Hoja: 3A_2025
Dimensiones: (44, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN      17:48:6

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 3B_2025
Dimensiones: (44, 27)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 17 Unnamed: 18 Unnamed: 19  Unnamed: 20  \
0        NaN  ...         NaN        HORA         NaN          NaN
1        NaN  ...         NaN    16:33:35         NaN          NaN

  Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 27 columns]

Hoja: 3C_2025
Dimensiones: (41, 28)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21  \
0        NaN  ...         NaN        HORA         NaN         NaN
1        NaN  ...         NaN     16:36:2         NaN         NaN

   Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 28 columns]

Hoja: 3D_2025
Dimensiones: (41, 27)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20  \
0        NaN  ...         NaN         NaN        HORA         NaN
1        NaN  ...         NaN         NaN    16:37:46         NaN

   Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 27 columns]

Hoja: 4A_2025
Dimensiones: (42, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     16:39:25

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 4B_2025
Dimensiones: (41, 28)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21  \
0        NaN  ...         NaN        HORA         NaN         NaN
1        NaN  ...         NaN    16:40:55         NaN         NaN

   Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 28 columns]

Hoja: 4C_2025
Dimensiones: (44, 28)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21  \
0        NaN  ...         NaN        HORA         NaN         NaN
1        NaN  ...         NaN    16:42:57         NaN         NaN

   Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 28 columns]

Hoja: 4D_2025
Dimensiones: (41, 28)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ... Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21  \
0        NaN  ...         NaN        HORA         NaN         NaN
1        NaN  ...         NaN     16:44:8         NaN         NaN

   Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 28 columns]

Hoja: 5A_2025
Dimensiones: (40, 25)
   Unnamed: 0  Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN         NaN        NaN        NaN        NaN        NaN
1         NaN         NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     17:30:34

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 5B_2025
Dimensiones: (40, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     16:57:28

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 5C_2025
Dimensiones: (41, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN     16:58:11

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]

Hoja: 5D_2025
Dimensiones: (40, 25)
   Unnamed: 0 Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN

                                          Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0  Estudiantes por grado y secci√≥n - 2025        ...        NaN        NaN
1                                                NaN        NaN        NaN

  Unnamed: 9  ...       Unnamed: 15 Unnamed: 16 Unnamed: 17  Unnamed: 18  \
0        NaN  ...  FECHA DE EMISI√ìN         NaN         NaN         HORA
1        NaN  ...        25/03/2025         NaN         NaN       17:4:8

  Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN

[2 rows x 25 columns]